# Site settings
title: Halleyin
legal_title: Halleyin Software Consultancy LTD
email: halleyinsoftware@hotmail.com
description: "Software and IT Consultancy Services"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/halleyin
  - title: instagram
    url: https://www.instagram.com/halleyinsoftware
  - title: envelope
    url: mailto:halleyinsoftware@hotmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Oxford House, 12 – 20 Oxford Street, Newbury, Berkshire, RG14 1JB

# Build settings
markdown: kramdown
permalink: pretty